#!/bin/bash
export IJULIA_NODEFAULTKERNEL=true
jupyter serverextension enable --py nbgitpuller --sys-prefix
python3 -m pip install --upgrade webio_jupyter_extension

julia --project=${REPO_DIR} create_sysimage.jl
